version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
     - 80:80
    networks:
      - gis_3ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - woni_static:/data/static/
      - woni_media:/data/media/

  django:
    image: woni:4
    networks:
      - gis_3ban_network
    volumes:
      - woni_static:/home/P_D/staticfiles/
      - woni_media:/home/P_D/media/
    secrets:
      - DJANGO_SECRET_KEY

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_3ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  gis_3ban_network:

volumes:
  woni_static:
  woni_media:
  gis_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true